<?php

define('IFE_MESSAGE_DEFAULT', -1);
define('IFE_MESSAGE_LEAVE', 0);
define('IFE_MESSAGE_ALTERNATE', 1);
define('IFE_MESSAGE_REMOVE', 2);

/**
 * @file
 * Drupal hooks
 *
 * @author Stijn De Meyere
 */


/**
 * Implements hook_menu().
 */
function ife_menu() {
  $items = array();

  $items['admin/config/user-interface/ife'] = array(
    'title' => 'Inline Form Errors',
    'description' => 'Administer which forms to use with field messages.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ife_settings_form'),
    'access arguments' => array('administer inline form errors'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'ife.settings.inc',
  );
  $items['admin/config/user-interface/ife/%ife_form_id/delete'] = array(
    'title' => 'Delete form_id',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ife_form_id_delete_form', 4),
    'access arguments' => array('administer inline form errors'),
    'type' => MENU_CALLBACK,
    'file' => 'ife.settings.inc',
  );

  return $items;
}

/**
 * Implements hook_permission().
 */
function ife_permission() {
  return array(
    'administer inline form errors' => array(
      'title' => t('administer inline form errors'),
      'description' => t('TODO Add a description for \'administer inline form errors\''),
    ),
  );
}

/**
 * Implements hook_help().
 */
function ife_help($path, $arg) {
  switch ($path) {
    case 'admin/help#ife':
      $output = '<p>' . t('IFE or Inline Form Errors allows you to place form submission error inline with the form elements. Three options are provided for setting your inline error behaviour. You can configure the default behaviour or override the behaviour on a per form basis. You can add as many forms as you like.') . '</p>';

      $output .= '<p>' . t('IFE provides three behaviours for the configured forms') . '</p>';

      $output .= '<ul>';
      $output .= '<li>' . t('<strong>Leave the messages in place</strong>, this option will copy the error messages and place them inline. The original error messages set by Drupal will remain in place') . '</li>';
      $output .= '<li>' . t("<strong>Show an alternate message</strong>, this option will replace the original messages with a generic error message such as 'Please correct all errors.'. This message can be set in the IFE configuration page. The original error messages are placed inline with the form elements") . '</li>';
      $output .= '<li>' . t('<strong>Remove all messages</strong>, this option will remove all error messages and place them inline with the form element') . '</li>';
      $output .= '</ul>';

      $output .= '<p>' . t('In all cases only the messages related to the form will be touched. All other messages will remain in tact.') . '</p>';

      return $output;

    case 'admin/config/user-interface/ife':
      return '<p>' . t('This page provides the interface for adding new forms to use inline errors. Just add the form_id of the forms you wish to alter. An * can be used as a wildcard. The default settings can be overridden on a per form basis.') . '</p>';
  }
}

/**
 * Menu loader function to fetch a form id.
 */
function ife_form_id_load($form_id) {
  $form_ids = ife_load_form_ids();

  foreach((array) $form_ids as $form_id_pattern => $form_settings) {
    if (ife_match_form_id($form_id, $form_id_pattern)) {
      return $form_settings;
    }
  }

  return FALSE;
}

/**
 * Check if a form ID pattern matches a given form ID.
 *
 * @param string $form_id
 *   The form ID to compare the pattern to.
 * @param string $form_id_pattern
 *   A form ID pattern. Ex. webform_*.
 *
 * @return boolean
 *   TRUE if the pattern matches the form_id, FALSE otherwise.
 */
function ife_match_form_id($form_id, $form_id_pattern) {
  // Convert form_id_pattern to a regular expression: replace /* with asterisks.
  $to_replace = array('/\\\\\*/');
  $replacements = array('.*');

  // Quote regular expression characters.
  $form_id_pattern_quoted = preg_quote($form_id_pattern, '/');

  // Create regular expression.
  $form_id_pattern_regex = '/^(' . preg_replace($to_replace, $replacements, $form_id_pattern_quoted) . ')$/';

  return (bool) preg_match($form_id_pattern_regex, $form_id);
}

/**
 * Implements hook_theme().
 */
function ife_theme() {
  return array(
    'ife_settings_form_ids' => array(
      'render element' => 'form',
      'file' => 'ife.theme.inc',
    ),
    'ife_form_element' => array(
      'render element' => 'element',
      'file' => 'ife.theme.inc',
    ),
  );
}

/**
 *  Load all form ids from the data base
 */
function ife_load_form_ids() {
  static $ife_form_ids;

  if ($ife_form_ids) {
    $form_ids = $ife_form_ids;
  }
  else {
    $cache = cache_get('ife_form_ids', 'cache');
    if ($cache) {
      $form_ids = $cache->data;
    }
  }

  if (empty($form_ids)) {

    $result = db_select('ife')
      ->fields('ife', array('form_id', 'field_types', 'status', 'display'))
      ->orderBy('form_id')
      ->execute();

    $form_ids = array();
    foreach ($result as $row) {
      $form_ids[$row->form_id] = $row;
    }
    cache_set('ife_form_ids', $form_ids, 'cache');
  }

  $ife_form_ids = $form_ids;
  return $ife_form_ids;
}

/**
 * Helper function to determine the display settings of a form
 */
function ife_form_id_display($form_id) {
  if ($form_id->display == IFE_MESSAGE_DEFAULT) {
    $display = variable_get('ife_display', IFE_MESSAGE_ALTERNATE);
  }
  else {
    $display = $form_id->display;
  }

  return $display;
}

/**
 * Implements hook_form_alter().
 */
function ife_form_alter(&$form, &$form_state, $form_id) {

  $status = variable_get('ife_show_everywhere', 0);
    if ($status && ! in_array($form_id, _ife_blacklist())) {
      $ife_options = new stdClass();
      $ife_options->status = TRUE;
      $ife_options->display = -1;
    }
    else {
      $ife_options = ife_form_id_load($form_id);
    }

  if ($ife_options && $ife_options->status) {
    $display = ife_form_id_display($ife_options);

    $form['#ife_display'] = $display;
    if (strpos($form_id, 'commerce_checkout_form_') === 0) {
      $form['#pre_render'][] = 'ife_commerce_checkout_form_pre_render';
    }
    else {
      $form['#validate'][] = 'ife_form_validator';
    }
  }

  // Print form_ids.
  if (variable_get('ife_show_form_ids', 0)) {
    $form['ife_form_id'] = array(
      '#markup' => t('Form ID: @form_id', array('@form_id' => $form_id)),
      '#weight' => -1000,
      '#access' => user_access('administer inline form errors'),
    );
  }
}

/**
 * Return an array of core form ids that are not compatible with ife
 */
function _ife_blacklist() {
  return array(
    'menu_overview_form',
    'block_admin_display_form',
    'book_admin_edit',
    'filter_admin_order',
    'profile_admin_overview',
    'taxonomy_overview_terms',
    'node_form', // attachment upload has tabledrag
  );
}

/**
 * Custom form validation handler
 */
function ife_form_validator(&$form, &$form_state) {
  static $global_error_processed = FALSE;
  // Do not validate on ajax requests, it may not work good in all cases.
  // See below
  if(!empty($_SERVER['HTTP_X_REQUESTED_WITH']) && strtolower($_SERVER['HTTP_X_REQUESTED_WITH']) == 'xmlhttprequest') {
    return TRUE;
  }
  if (empty($form['#form_id'])) {
    return TRUE;
  }
  $form_errors = form_get_errors();
  if (!empty($form_errors)) {
    ife_element_errors_set($form, $form['#ife_display']);

    if ($form['#ife_display'] == IFE_MESSAGE_ALTERNATE && empty($global_error_processed[$form['#form_id']])) {
      $message = filter_xss_admin(variable_get('ife_general_message', 'Please correct all highlighted errors and try again.'));
      drupal_set_message($message, 'error');

      $global_error_processed[$form['#form_id']] = TRUE;
    }
  }

  // This function returns TRUE, because is does not really validate anything
  // and to support commerce modules this function needs to have a return value.
  // Change: the commerce module does not need anymore this, we do not use
  // the ife_commerce_checkout_pane_info_alter() anymore.
  return TRUE;
}

/**
 * General function to check if a form element has an error.
 * This function will then set the error on the element to be later used
 * by our theming function theme_ife_form_element().
 */
function ife_element_errors_set(&$element, $display, $carry_down = FALSE) {

  // Check for errors and settings
  $errors = form_get_errors();
  if (!empty($element['#parents'])) {
    $element_id = implode('][', $element['#parents']);
    if (!empty($errors[$element_id])) {
      $error_message = $errors[$element_id];

      // To show only one message we do the following steps:
      // 1. We first backup all the error messages into a variable.
      $tmp_error_messages = isset($_SESSION['messages']['error']) ? $_SESSION['messages']['error'] : array();
      // 2. We replace the error messages in the session with the error we want
      // to show.
      $_SESSION['messages']['error'] = array($error_message);
      // 3. We prepend the error messages to the element, by adding them in the
      // #prefix of the element.
      if (empty($element['#prefix'])) {
        $element['#prefix'] = '';
      }
      $element['#prefix'] = theme('status_messages', array('display' => 'error')) . $element['#prefix'];
      // 4. We restore the errors from the backup into the session.
      if (!empty($tmp_error_messages)) {
        $_SESSION['messages']['error'] = $tmp_error_messages;
      }

      // Check to see if we should remove or leave the error message in the
      // session.
      if (isset($display) && $display != IFE_MESSAGE_LEAVE && isset($_SESSION['messages']['error'])) {
        // Code here!
        $error_id = array_search($error_message, $_SESSION['messages']['error']);
        if ($error_id !== FALSE) {
          unset($_SESSION['messages']['error'][$error_id]);
          if (count($_SESSION['messages']['error']) <= 0) {
            unset($_SESSION['messages']['error']);
          }
          else {
            $_SESSION['messages']['error'] = array_values($_SESSION['messages']['error']);
          }
        }
      }
    }
  }

  // Recurse through all children.
  foreach (element_children($element) as $key) {
    if (isset($element[$key]) && $element[$key]) {
      ife_element_errors_set($element[$key], $display, $carry_down);
    }
  }
}

/**
 * Pre render callback for the commerce checkout form.
 */
function ife_commerce_checkout_form_pre_render(&$element) {
  $validated_forms = drupal_static('drupal_validate_form', array());
  if (!empty($validated_forms[$element['#form_id']]) && $errors = form_get_errors()) {
    // A fake form_state, we do not need it in the ife_form_validator().
    $form_state = array();
    ife_form_validator($element, $form_state);
    foreach (element_children($element) as $child) {
      if (!empty($element[$child][$child . '_messages'])) {
        unset($element[$child][$child . '_messages']);
      }
    }
  }
  return $element;
}

/**
 * Implements hook_commerce_checkout_pane_info_alter().
 *
 * We do the integration with the commerce in another way, by adding a
 * pre_render callback in the hook_form_alter(). We had some issues with adding
 * validation callbacks.
 */
/*
function ife_commerce_checkout_pane_info_alter(&$panes) {
  foreach ((array) $panes as $key => $pane) {
    if (!isset($panes[$key]['callbacks'])) {
      $panes[$key]['callbacks'] = array(
          'checkout_form_validate' => 'ife_form_validator',
      );
    }
  }
}
*/
